[2025-08-07T16:03:35.158+0700] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ekstrak_pdf_dag.generate_embeddings manual__2025-08-07T09:02:05.363110+00:00 [queued]>
[2025-08-07T16:03:35.171+0700] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ekstrak_pdf_dag.generate_embeddings manual__2025-08-07T09:02:05.363110+00:00 [queued]>
[2025-08-07T16:03:35.171+0700] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-08-07T16:03:35.200+0700] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): generate_embeddings> on 2025-08-07 09:02:05.363110+00:00
[2025-08-07T16:03:35.210+0700] {standard_task_runner.py:57} INFO - Started process 118732 to run task
[2025-08-07T16:03:35.222+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ekstrak_pdf_dag', 'generate_embeddings', 'manual__2025-08-07T09:02:05.363110+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpwzhhxwz6']
[2025-08-07T16:03:35.223+0700] {standard_task_runner.py:85} INFO - Job 13: Subtask generate_embeddings
[2025-08-07T16:03:35.315+0700] {task_command.py:416} INFO - Running <TaskInstance: ekstrak_pdf_dag.generate_embeddings manual__2025-08-07T09:02:05.363110+00:00 [running]> on host dwmhr.localdomain
[2025-08-07T16:03:35.437+0700] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ekstrak_pdf_dag' AIRFLOW_CTX_TASK_ID='generate_embeddings' AIRFLOW_CTX_EXECUTION_DATE='2025-08-07T09:02:05.363110+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-07T09:02:05.363110+00:00'
[2025-08-07T16:03:35.443+0700] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dwmhr/pln/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/dwmhr/pln/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dwmhr/pln/airflow/dags/etl.py", line 16, in generate_embeddings_wrapper
    from generate_embedding import generate_embeddings
  File "/home/dwmhr/pln/scripts/generate_embedding.py", line 3, in <module>
    from sentence_transformers import SentenceTransformer
ModuleNotFoundError: No module named 'sentence_transformers'
[2025-08-07T16:03:35.453+0700] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ekstrak_pdf_dag, task_id=generate_embeddings, execution_date=20250807T090205, start_date=20250807T090335, end_date=20250807T090335
[2025-08-07T16:03:35.476+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task generate_embeddings (No module named 'sentence_transformers'; 118732)
[2025-08-07T16:03:35.515+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-07T16:03:35.547+0700] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
